flowchart TD
  subgraph Actors
    Issuer
    Holder
    Verifier
  end

  subgraph CLIs
    deploy
    register
    update
    anchor
    resolve
    checkDid
    verifyVc
  end

  subgraph OffChain
    IssuerPod[(Issuer Pod)]
    SubjectPod[(Subject Pod)]
    IssuerDidDoc[Issuer DID Document]
    VCFile[Verifiable Credential]
  end

  subgraph OnChain
    DIDRegistry
  end

  Issuer --> deploy
  Issuer --> register
  Issuer --> update
  Issuer --> anchor
  Verifier --> resolve
  Verifier --> checkDid
  Verifier --> verifyVc

  deploy --> DIDRegistry

  register --> IssuerDidDoc
  register --> DIDRegistry

  update --> IssuerDidDoc
  update --> DIDRegistry

  anchor --> VCFile
  anchor --> DIDRegistry

  resolve --> DIDRegistry

  checkDid --> IssuerDidDoc
  checkDid --> DIDRegistry

  verifyVc --> VCFile
  verifyVc --> DIDRegistry

  IssuerPod --- IssuerDidDoc
  SubjectPod --- VCFile